### ISSUE TITLE
Access to the protobuf file for graph creation

### ISSUE THREAD

**Issue by mcleantom** [infality/ship-routing-final#1]
Hey, I was just wondering if it is possible to have the protobuf file to run `cargo run --release --bin extract <pbf file>`

Thanks!

**Comment by infality** [comment]
Hey, unfortunately I can't provide them here since they are very big and updated constantly.
The wiki page provides links to some download sites https://wiki.openstreetmap.org/wiki/PBF_Format

**Comment by mcleantom** [comment]
Thanks for the reply, do you know if it is the full planet pbf file I need to download or just the coast lines cleaned? I saw another git repository that is also doing ship routing with OSM data and they download this file - [https://cloud.p-fruck.de/s/pf9JfNabwDjrNL8/download/planet-coastlinespbf-cleaned.osm.pbf](https://cloud.p-fruck.de/s/pf9JfNabwDjrNL8/download/planet-coastlinespbf-cleaned.osm.pbf)

**Comment by infality** [comment]
I remember using a full planet pbf and it took a lot of time to extract the coastlines from it.
If you have a trimmed pbf with just coastlines it could work as well and be much faster.
